apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfzt.fullname" . }}-cache-store
  namespace: {{ include "cfzt.namespace" . }}
  labels:
    {{- include "cfzt.labels" . | nindent 4 }}
    app.kubernetes.io/component: caching
spec:
  type: {{ .Values.cacheStore.service.type | default "ClusterIP" }}
  selector:
    {{- include "cfzt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: caching
  ports:
    - name: http
      port: {{ .Values.cacheStore.service.port | default 8007 }}
      targetPort: http
      protocol: TCP
