apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: cfzt
  labels:
    app: auth-api
    component: authentication
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
