apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfzt.fullname" . }}-analytics
  namespace: {{ include "cfzt.namespace" . }}
  labels:
    {{- include "cfzt.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  type: {{ .Values.analytics.service.type | default "ClusterIP" }}
  selector:
    {{- include "cfzt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
  ports:
    - name: http
      port: {{ .Values.analytics.service.port | default 8009 }}
      targetPort: http
      protocol: TCP
