apiVersion: v1
kind: Service
metadata:
  name: zk-proofs
  namespace: cfzt
  labels:
    app: zk-proofs
    component: zero-knowledge
spec:
  type: ClusterIP
  selector:
    app: zk-proofs
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
    - name: grpc
      port: 50053
      targetPort: 50053
      protocol: TCP
