apiVersion: v2
name: cfzt
description: Continuous Face Zero Trust — Helm Chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - zero-trust
  - face-auth
  - quantum
  - pqc
  - zk-proofs
maintainers:
  - name: quantumworld-dpdns-io
