apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: face-ml
  namespace: cfzt
  labels:
    app: face-ml
    component: ml-inference
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: face-ml
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
