apiVersion: v1
kind: Service
metadata:
  name: cache-store
  namespace: cfzt
  labels:
    app: cache-store
    component: caching
spec:
  type: ClusterIP
  selector:
    app: cache-store
  ports:
    - name: http
      port: 8007
      targetPort: 8007
      protocol: TCP
