apiVersion: v1
kind: Service
metadata:
  name: edge-gateway
  namespace: cfzt
  labels:
    app: edge-gateway
    component: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: edge-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8787
      protocol: TCP
