apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: auth-api
  namespace: cfzt
spec:
  host: auth-api
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        h2UpgradePolicy: DEFAULT
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
